// Auto-converted from the original static HTML. Each original top-level section is isolated as a React component.

export function Section1() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"breadcrumb-section\">\n<div class=\"breadcrumb-content-wrap\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-xl-9 col-lg-10\">\n<div class=\"breadcrumb-content\">\n<h1>About ANJANI INDUSTRIES</h1>\n</div>\n</div>\n</div>\n</div>\n</div>\n<div class=\"breadcrumb-img\">\n<img alt=\"\" src=\"/assets/img/about-banner.jpg\"/>\n</div>\n</div>" }} />; }
export function Section2() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"about-page-section mb-80\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-lg-12\">\n<div class=\"red-box-content\">\n<h2>Established in 1990, ANJANI INDUSTRIES</h2>\n<h4>is one of India’s leading manufacturers of textile dyeing and processing machinery, \nbacked by over 36 years of engineering excellence.</h4>\n</div>\n<div class=\"about-box-padding\">\n<p>Since our inception, we have been committed to delivering innovative, reliable, and energy-efficient textile processing solutions that empower manufacturers to enhance productivity, improve dyeing quality, and reduce operating costs.</p>\n<p>We specialize in the design, engineering, and manufacturing of technologically advanced textile dyeing machinery that combines precision engineering, robust construction, and intelligent automation to meet the evolving demands of the global textile industry.</p>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section3() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"about-page-section mb-80\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-lg-12\">\n<div class=\"section-title text-center mb-4\">\n<h2 class=\"mb-2\">Our Products</h2>\n<h6>Our comprehensive product portfolio includes:</h6>\n</div>\n</div>\n</div>\n<div class=\"row\">\n<div class=\"col-lg-6\"><div class=\"about-pro-lit\">Low Liquor Ratio ECO+ Soft Flow Dyeing Machines</div></div>\n<div class=\"col-lg-6\"><div class=\"about-pro-lit\">Weight Reduction (Scouring) Machines</div></div>\n<div class=\"col-lg-6\"><div class=\"about-pro-lit\">U-Type Jet Dyeing Machines</div></div>\n<div class=\"col-lg-6\"><div class=\"about-pro-lit\">Caustic Recovery Plants</div></div>\n<div class=\"col-lg-6\"><div class=\"about-pro-lit\">Long Tube Rapid Jet Dyeing Machines</div></div>\n<div class=\"col-lg-6\"><div class=\"about-pro-lit\">Customized Textile Processing Machinery</div></div>\n</div>\n<div class=\"row\">\n<div class=\"col-lg-12\">\n<div class=\"text-center mb-4 italic-font\">\n<p>Every machine is meticulously engineered to minimize water, steam, and power consumption while maximizing productivity, reducing processing time, and delivering consistent dyeing performance.</p>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section4() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"home1-about-section\">\n<div class=\"container-fluid\">\n<div class=\"row align-items-center g-0\">\n<div class=\"col-lg-6 wow animate fadeInRight\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"about-img\">\n<img alt=\"\" class=\"w-100\" src=\"/assets/img/Manufacturing.jpg\"/>\n</div>\n</div>\n<div class=\"col-lg-6 wow animate fadeInLeft\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"about-full-box-page-left\">\n<div class=\"section-title mb-3\">\n<h2>Manufacturing Excellence</h2>\n</div>\n<div class=\"about-content\">\n<p>Our corporate headquarters and state-of-the-art manufacturing facility are located in Surat, Gujarat, India, spanning over 45,000 sq. ft. Equipped with modern manufacturing infrastructure, advanced R&amp;D capabilities, precision machining, stringent quality control systems, and dedicated after-sales technical support, we deliver complete textile processing solutions under one roof.</p>\n<p>Every stage of manufacturing—from design and fabrication to assembly, testing, and commissioning—is carried out with strict adherence to international quality standards to ensure long-lasting performance and reliability.</p>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section5() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"home1-about-section mb-80\">\n<div class=\"container-fluid\">\n<div class=\"row align-items-center g-0\">\n<div class=\"col-lg-6 wow animate fadeInLeft\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"about-full-box-page-right\">\n<div class=\"section-title mb-3\">\n<h2>Innovation Driven by Experience</h2>\n</div>\n<div class=\"about-content\">\n<p>For over 36 years, Anjani Industries has continuously invested in research, product development, and engineering innovation to create machinery that meets the changing needs of modern textile processors.</p>\n<p>Our focus on sustainable engineering enables customers to reduce water, steam, energy, and chemical consumption while achieving superior dyeing quality and lower production costs.</p>\n<p>Today, textile manufacturers across India and international markets trust Anjani Industries for dependable machinery, technical expertise, and responsive after-sales support.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-6 wow animate fadeInRight\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"about-img\">\n<img alt=\"\" class=\"w-100\" src=\"/assets/img/Experience.jpg\"/>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section6() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"mb-80\">\n<div class=\"container\">\n<div class=\"row justify-content-center wow animate fadeInDown\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"col-xl-12 col-lg-12\">\n<div class=\"section-title text-center mb-4\">\n<h2 class=\"mb-2\">Quality Assurance</h2>\n<h6 class=\"mb-0\">As an ISO 9001:2015 Certified Company, quality is at the heart of everything we do.</h6>\n<p>Every machine undergoes rigorous quality inspections and performance testing before dispatch, ensuring it meets our uncompromising standards for reliability, efficiency, and durability.</p>\n</div>\n</div>\n</div>\n</div>\n<div class=\"container\">\n<div class=\"leadership-box\">\n<div class=\"row align-items-center g-0\">\n<div class=\"col-lg-4\"><img class=\"w-100\" src=\"/assets/img/dhruv-patel.jpg\"/></div>\n<div class=\"col-lg-8\">\n<div class=\"p-5 text-white\">\n<h3 class=\"text-white\">Leadership Message</h3>\n<p class=\"text-white\">“At Anjani Industries, we never compromise on the quality of our products. Our commitment is to deliver innovative textile dyeing solutions that create lasting value for our customers through quality, technology, and exceptional service.”</p>\n<h5 class=\"text-white\">- Dhruv Patel, Owner</h5>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section7() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"mb-80 inner-contact-section two\">\n<div class=\"container-fluid\">\n<div class=\"row justify-content-center wow animate fadeInDown\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"col-xl-12 col-lg-12 col-md-8\">\n<div class=\"section-title text-left mb-4\">\n<h2>Why Textile manufacturers <br/>\n<div class=\"red\">trust Anjani Industries?</div></h2>\n</div>\n</div>\n</div>\n<div class=\"row\">\n<div class=\"col-lg-6\">\n<div class=\"manufacturers-list\">\n<h5>36+ Years of Engineering Excellence\n<p>As an ISO 9001:2015 Certified Company, quality is at the heart of everything we do.</p>\n</h5></div>\n<div class=\"manufacturers-list\">\n<h5>Quality • Technology • Metrology • Service \n<p> The four pillars that drive everything we do.</p>\n</h5></div>\n<div class=\"manufacturers-list\">\n<h5>ISO 9001:2015 Certified Company  \n<p>Committed to international quality standards.</p>\n</h5></div>\n<div class=\"manufacturers-list\">\n<h5>45,000 sq. ft. Modern Manufacturing Facility\n<p>Equipped with advanced manufacturing and testing infrastructure.</p>\n</h5></div>\n</div>\n<div class=\"col-lg-6\">\n<div class=\"manufacturers-list\">\n<h5>Innovative &amp; Energy-Efficient Dyeing Machinery \n<p>Designed to reduce water, steam, power, and operating costs.</p>\n</h5></div>\n<div class=\"manufacturers-list\">\n<h5>Dedicated Research &amp; Development \n<p>Continuously developing technologies for the evolving textile industry.</p>\n</h5></div>\n<div class=\"manufacturers-list\">\n<h5>Reliable After-Sales Technical Support  \n<p>Prompt service and long-term customer assistance.</p>\n</h5></div>\n<div class=\"manufacturers-list\">\n<h5>Trusted by Textile Manufacturers Across India &amp; International Markets   \n<p>Building lasting partnerships through quality and performance.</p>\n</h5></div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section8() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"mb-40\">\n<div class=\"container-fluid\">\n<div class=\"row justify-content-center wow animate fadeInDown\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"col-xl-12 col-lg-12 col-md-8\">\n<div class=\"section-title text-left mb-4\">\n<h2>Health, Safety &amp; Environment</h2>\n</div>\n<p class=\"mb-1\">The safety of our employees, customers, and manufacturing operations is our highest priority.</p>\n<p class=\"mb-1\">We maintain a safe and healthy workplace through modern manufacturing practices, advanced production technologies, regular safety training, \nand strict quality and safety procedures.</p>\n<p class=\"mb-1\">Our commitment to environmental responsibility is reflected in the development of resource-efficient textile processing machinery that helps \nreduce water, energy, and steam consumption, contributing to a more sustainable textile industry.</p>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section9() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"mb-80\">\n<div class=\"container-fluid\">\n<div class=\"row justify-content-center wow animate fadeInDown\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"col-xl-12 col-lg-12 col-md-8\">\n<div class=\"section-title text-left mb-4\">\n<h2>Our Commitment</h2>\n</div>\n<h6>Quality • Technology • Metrology • Service</h6>\n<p>These four pillars define everything we do and continue to guide Anjani Industries in delivering world-class textile dyeing and processing solutions for customers across the globe.</p>\n</div>\n</div>\n</div>\n</div>" }} />; }

export default function AboutUsSections() { return <>
  <Section1 />
  <Section2 />
  <Section3 />
  <Section4 />
  <Section5 />
  <Section6 />
  <Section7 />
  <Section8 />
  <Section9 />
</>; }