// Auto-converted from the original static HTML. Each original top-level section is isolated as a React component.

export function Section1() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"breadcrumb-section\">\n<div class=\"breadcrumb-content-wrap\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-xl-9 col-lg-10\">\n<div class=\"breadcrumb-content\">\n<h1>Our Core Values &amp; Ethics</h1>\n</div>\n</div>\n</div>\n</div>\n</div>\n<div class=\"breadcrumb-img\">\n<img alt=\"\" src=\"/assets/img/values-banner.jpg\"/>\n</div>\n</div>" }} />; }
export function Section2() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"about-page-section mb-80\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-lg-12 col-12\">\n<div class=\"red-box-content\">\n<div class=\"row align-items-center\">\n<div class=\"col-lg-6 text-lg-center text-start\">\n<h2>Entrepreneurial Spirit</h2>\n</div>\n<div class=\"col-lg-6 values-border\">\n<h4>Thinking Beyond Boundaries</h4>\n<p class=\"text-white mb-0\">We embrace innovation,\n                                        encourage creative thinking, and\n                                        continuously pursue new opportunities to\n                                        improve our products, processes, and\n                                        customer experience.</p>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section3() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"about-page-section mb-80\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-lg-12\">\n<div class=\"section-title text-center mb-4\">\n<h2 class=\"mb-5 red\">One Anjani Family</h2>\n</div>\n</div>\n</div>\n<div class=\"row\">\n<div class=\"col-lg-6\">\n<div class=\"velue-box\">\n<img src=\"/assets/img/icon/core_value/core_value1.png\"/>\n<div>\n<h4>Growing Together, Succeeding Together</h4>\n<p>We believe every employee, customer,\n                                    supplier, and business partner is part of\n                                    the Anjani family. Through trust,\n                                    collaboration, and mutual respect, we build\n                                    lasting relationships and achieve shared\n                                    success.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-6\">\n<div class=\"velue-box\">\n<img src=\"/assets/img/icon/core_value/core_value2.png\"/>\n<div>\n<h4>Innovation</h4>\n<p>We continuously develop advanced technologies\n                                    to create efficient, reliable, and\n                                    sustainable textile processing\n                                    solutions.</p>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section4() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"mb-50 inner-contact-section two\">\n<div class=\"container-fluid\">\n<div class=\"row align-items-center\">\n<div class=\"col-lg-6\">\n<div class=\"section-title text-left mb-4\">\n<h2>Quality</h2>\n<p class=\"pt-2\">We never compromise on quality and strive for excellence in every machine we manufacture.</p>\n</div>\n<div class=\"section-title text-left mb-4\">\n<h5>Integrity</h5>\n<p class=\"pt-2\">We conduct our business with honesty, transparency, and professionalism.</p>\n</div>\n</div>\n<div class=\"col-lg-6\">\n<img alt=\"\" class=\"w-100\" src=\"/assets/img/quality.jpg\"/>\n</div>\n</div>\n</div>\n</div>" }} />; }
export function Section5() { return <div dangerouslySetInnerHTML={{ __html: "<div class=\"mb-50 values-ethics-section\">\n<div class=\"container-fluid\">\n<div class=\"row justify-content-center wow animate fadeInDown\" data-wow-delay=\"200ms\" data-wow-duration=\"1500ms\">\n<div class=\"col-xl-12 col-lg-12 col-md-8\">\n<div class=\"section-title text-center mb-5\">\n<h2>Customer Commitment</h2>\n<p class=\"pt-2\">We build long-term partnerships by delivering dependable products and exceptional after-sales support.</p>\n</div>\n</div>\n</div>\n<div class=\"row\">\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Ethics Of Anjani Industries</h4>\n<p class=\"mb-0\">Treat people as you want to be treated.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Respect for others</h4>\n<p class=\"mb-0\">Treat people as you want to be treated.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Integrity and honesty</h4>\n<p class=\"mb-0\">Tell the truth and avoid any wrongdoing to the best of your ability.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Justice</h4>\n<p class=\"mb-0\">Make sure you’re objective and fair and don’t disadvantage others.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Lawfulness</h4>\n<p class=\"mb-0\">Know and follow the law – always.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Competence and accountability </h4>\n<p class=\"mb-0\">Work hard and be responsible for your work.</p>\n</div>\n</div>\n</div>\n<div class=\"col-lg-3\">\n<div class=\"customer-box\">\n<div>\n<h4>Teamwork </h4>\n<p class=\"mb-0\">Collaborate and ask for help.</p>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>" }} />; }

export default function ValuesEthicsSections() { return <>
  <Section1 />
  <Section2 />
  <Section3 />
  <Section4 />
  <Section5 />
</>; }